/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InstantRouteImport } from './routes/instant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTradeResultsRouteImport } from './routes/admin.trade-results'
import { Route as AdminSalesTeamRouteImport } from './routes/admin.sales-team'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminPromoCodesRouteImport } from './routes/admin.promo-codes'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksCompetitionsRolloverRouteImport } from './routes/api/public/hooks/competitions-rollover'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstantRoute = InstantRouteImport.update({
  id: '/instant',
  path: '/instant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTradeResultsRoute = AdminTradeResultsRouteImport.update({
  id: '/admin/trade-results',
  path: '/admin/trade-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesTeamRoute = AdminSalesTeamRouteImport.update({
  id: '/admin/sales-team',
  path: '/admin/sales-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/admin/referrals',
  path: '/admin/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoCodesRoute = AdminPromoCodesRouteImport.update({
  id: '/admin/promo-codes',
  path: '/admin/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/admin/competitions',
  path: '/admin/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/admin/chats',
  path: '/admin/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCompetitionsRolloverRoute =
  ApiPublicHooksCompetitionsRolloverRouteImport.update({
    id: '/api/public/hooks/competitions-rollover',
    path: '/api/public/hooks/competitions-rollover',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/checkout': typeof CheckoutRoute
  '/competition': typeof CompetitionRoute
  '/dashboard': typeof DashboardRoute
  '/instant': typeof InstantRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sales-team': typeof AdminSalesTeamRoute
  '/admin/trade-results': typeof AdminTradeResultsRoute
  '/admin/users': typeof AdminUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/competitions-rollover': typeof ApiPublicHooksCompetitionsRolloverRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/checkout': typeof CheckoutRoute
  '/competition': typeof CompetitionRoute
  '/dashboard': typeof DashboardRoute
  '/instant': typeof InstantRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sales-team': typeof AdminSalesTeamRoute
  '/admin/trade-results': typeof AdminTradeResultsRoute
  '/admin/users': typeof AdminUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin': typeof AdminIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/competitions-rollover': typeof ApiPublicHooksCompetitionsRolloverRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/checkout': typeof CheckoutRoute
  '/competition': typeof CompetitionRoute
  '/dashboard': typeof DashboardRoute
  '/instant': typeof InstantRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sales-team': typeof AdminSalesTeamRoute
  '/admin/trade-results': typeof AdminTradeResultsRoute
  '/admin/users': typeof AdminUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/competitions-rollover': typeof ApiPublicHooksCompetitionsRolloverRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/checkout'
    | '/competition'
    | '/dashboard'
    | '/instant'
    | '/reset-password'
    | '/reviews'
    | '/trust'
    | '/unsubscribe'
    | '/admin/accounts'
    | '/admin/chats'
    | '/admin/competitions'
    | '/admin/documents'
    | '/admin/emails'
    | '/admin/orders'
    | '/admin/promo-codes'
    | '/admin/referrals'
    | '/admin/reviews'
    | '/admin/sales-team'
    | '/admin/trade-results'
    | '/admin/users'
    | '/email/unsubscribe'
    | '/admin/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/competitions-rollover'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/challenges'
    | '/checkout'
    | '/competition'
    | '/dashboard'
    | '/instant'
    | '/reset-password'
    | '/reviews'
    | '/trust'
    | '/unsubscribe'
    | '/admin/accounts'
    | '/admin/chats'
    | '/admin/competitions'
    | '/admin/documents'
    | '/admin/emails'
    | '/admin/orders'
    | '/admin/promo-codes'
    | '/admin/referrals'
    | '/admin/reviews'
    | '/admin/sales-team'
    | '/admin/trade-results'
    | '/admin/users'
    | '/email/unsubscribe'
    | '/admin'
    | '/lovable/email/suppression'
    | '/api/public/hooks/competitions-rollover'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/challenges'
    | '/checkout'
    | '/competition'
    | '/dashboard'
    | '/instant'
    | '/reset-password'
    | '/reviews'
    | '/trust'
    | '/unsubscribe'
    | '/admin/accounts'
    | '/admin/chats'
    | '/admin/competitions'
    | '/admin/documents'
    | '/admin/emails'
    | '/admin/orders'
    | '/admin/promo-codes'
    | '/admin/referrals'
    | '/admin/reviews'
    | '/admin/sales-team'
    | '/admin/trade-results'
    | '/admin/users'
    | '/email/unsubscribe'
    | '/admin/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/competitions-rollover'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  CheckoutRoute: typeof CheckoutRoute
  CompetitionRoute: typeof CompetitionRoute
  DashboardRoute: typeof DashboardRoute
  InstantRoute: typeof InstantRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPromoCodesRoute: typeof AdminPromoCodesRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSalesTeamRoute: typeof AdminSalesTeamRoute
  AdminTradeResultsRoute: typeof AdminTradeResultsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCompetitionsRolloverRoute: typeof ApiPublicHooksCompetitionsRolloverRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instant': {
      id: '/instant'
      path: '/instant'
      fullPath: '/instant'
      preLoaderRoute: typeof InstantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trade-results': {
      id: '/admin/trade-results'
      path: '/admin/trade-results'
      fullPath: '/admin/trade-results'
      preLoaderRoute: typeof AdminTradeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales-team': {
      id: '/admin/sales-team'
      path: '/admin/sales-team'
      fullPath: '/admin/sales-team'
      preLoaderRoute: typeof AdminSalesTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo-codes': {
      id: '/admin/promo-codes'
      path: '/admin/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/admin/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/admin/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/competitions-rollover': {
      id: '/api/public/hooks/competitions-rollover'
      path: '/api/public/hooks/competitions-rollover'
      fullPath: '/api/public/hooks/competitions-rollover'
      preLoaderRoute: typeof ApiPublicHooksCompetitionsRolloverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  CheckoutRoute: CheckoutRoute,
  CompetitionRoute: CompetitionRoute,
  DashboardRoute: DashboardRoute,
  InstantRoute: InstantRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPromoCodesRoute: AdminPromoCodesRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSalesTeamRoute: AdminSalesTeamRoute,
  AdminTradeResultsRoute: AdminTradeResultsRoute,
  AdminUsersRoute: AdminUsersRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminIndexRoute: AdminIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCompetitionsRolloverRoute:
    ApiPublicHooksCompetitionsRolloverRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
